testrail:
  baseUrl: https://olegtestrail.testrail.io/
  #${TESTRAIL_BASE_URL?:unknown}
  login: olleglion02@gmail.com
  #${TESTRAIL_LOGIN?:unknown}
  token: 8MbUxxpgfyPi6qH.QRU2-6yWeK/sIdYqVFgqyg2l7
  #${TESTRAIL_TOKEN?:unknown}
  project:
    id: 2
  suite:
    id: 9

spring:
  main:
    web-application-type: none
