name: Generate File and Create Pull Request

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write
  actions: write

env:
  label: " tests "
  gradle_cmd: ./gradlew --parallel --build-cache
    -PAWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
    -PAWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
    -Psystems.ajax.mavenRepository.snapshots=${{ secrets.SNAPSHOTS_REPOSITORY }}
    -Psystems.ajax.mavenRepository.releases=${{ secrets.RELEASES_REPOSITORY }}

jobs:
  generate-and-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Get PR labels
        id: pr-labels
        uses: irby/get-labels-on-push@v1.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate PR branch name
        id: generate-branch
        if: ${{ !cancelled() && contains(steps.pr-labels.outputs.labels, env.label) }}
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message || 'added-generated-changes' }}"
          NEW_BRANCH="autogenerated/$(echo $COMMIT_MESSAGE | tr ' ' '-')"
          echo "new_branch=$NEW_BRANCH" >> $GITHUB_ENV

      - name: Create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        if: ${{ steps.generate-branch.outcome != 'skipped'  }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ env.new_branch }}

      - name: Checkout new branch
        id: checkout-branch
        uses: actions/checkout@v4
        if: ${{ !cancelled() && contains(steps.pr-labels.outputs.labels, env.label) }}
        with:
          ref: ${{ env.new_branch }}

      - name: Build with Gradle
        run: ${gradle_cmd} build -x deltaCoverage -x test

      - name: Run Main Code
        if: ${{ steps.checkout-branch.outcome != 'skipped'  }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          ${gradle_cmd} bootRun
          git status

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        if: ${{ steps.generate-branch.outcome != 'skipped'  }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.new_branch }}
          commit-message: "Automatically added changed files with generated ids"
          base: 'main'

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        if: ${{ steps.generate-branch.outcome != 'skipped'  }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
